// SPDX-License-Identifier: Apache-2.0 OR MIT
// GENERATED by gen_bindings.py. Do not edit.
//
// Method hashes come from extension_api.json. Each one is identical in Godot 4.0, 4.1, 4.2, 4.3, 4.4, 4.5,
// so one binary serves the whole line. gen_bindings.py re-checks that and fails if
// a future release changes a signature.
#ifndef GDEXTENSION_SYMBOLS_H
#define GDEXTENSION_SYMBOLS_H

#define CINEFORM_GODOT_FLOOR "4.2"

#define HASH_MOVIEWRITER_ADD_WRITER        4023702871ULL
#define HASH_OS_GET_PROCESSOR_COUNT        3905245786ULL
#define HASH_IMAGE_CREATE_FROM_DATA        299398494ULL
#define HASH_IMAGE_CONVERT                 2120693146ULL
#define HASH_IMAGE_GET_DATA                2362200018ULL
#define HASH_IMAGE_GET_FORMAT              3847873762ULL
#define HASH_IMAGE_GET_WIDTH               3905245786ULL
#define HASH_IMAGE_GET_HEIGHT              3905245786ULL

#endif // GDEXTENSION_SYMBOLS_H
